### ISSUE TITLE
SQL: Remplacer le champs a_valider par valide

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-adresse-module#13]
Une fois https://github.com/3liz/qgis-gestion_base_adresse-plugin/issues/57 implémenté, il faudra : 
- [x] modifier https://github.com/3liz/lizmap-adresse-module/blob/master/adresse/classes/update.class.php#L16 `'validation' =>'UPDATE adresse.point_adresse SET a_valider = False WHERE id_point = %s::integer;`
- [x] ajouter une nouvelle ligne à `update::sql` `'validation_new' =>'UPDATE adresse.point_adresse SET valide = True WHERE id_point = %s::integer;`
- [x] Utiliser la bonne requête en fonction de la version de la base de données.

**Comment by rldhont** [comment]
La base de données a été modifiée https://github.com/3liz/qgis-gestion_base_adresse-plugin/pull/58

**Comment by drillinP** [comment]
#14 @rldhont
