### ISSUE TITLE
Formulaire Voie: Ajouter un bouton d'inversion de géométrie

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-adresse-module#15]
En plus du bouton déjàé présent dans la popup, il faudrait coder en JavaScript dans le formulaire de la couche Voie un bouton inversant la géométrie.

Il est possible de le faire facilement avec OpenLayers : 
* Récupérer la géométrie en cours d'édition `feat.geometry`
* Récupérer le tableau des points `geom.getVertices()`
* Inverser ce tableau `vertices.reverse()`
* Créer une nouvelle géométrie `new OpenLayers.Geometry.LineString(vertices)`
* Modifier la géométrie de l'objet en édition

**Comment by drillinP** [comment]
@rldhont dans le fomulaire d'édition ?  pas la popup !

**Comment by rldhont** [comment]
Cette fonctionnalité est native dans lizmap 3.5

**Comment by Gustry** [comment]
Je pense que je peux clore le ticket alors.
