### ISSUE TITLE
Doc: Export de document - mise en forme

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-adresse-module#26]
Il y a une erreur dans la mise en forme de ce paragraphe : 

> Comme on le voit ci-dessous le module ajoute un mini-dock, il est représenté dans le menu par une icône de route (dernier élément du menu). Sur ce dock on y trouve un menu de téléchargement des documents pour la gestion des voie et adresse. Il y a: * l'export BAL qui est un export CSV des adresses au format BAL; * l'export des voies à délibérer; * l'export SNA.

**Comment by drillinP** [comment]
Commit 79cdf1d0c9341051b97e1e2ac90d2daca0ff3c54
