### ISSUE TITLE
Modification du nom de la vue export_bal en v_export_bal

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-adresse-module#31]
Dans la version 0.7.0 du plugin , le nom de la vue `export_bal` change en `v_export_bal` et le champs `date_derniere_maj` en `date_der_maj`  https://github.com/3liz/qgis-gestion_base_adresse-plugin/issues/86

Ce changement concerne `adresse/classes/search.class.php`

**Comment by drillinP** [comment]
commit: 8b83234fdbc118414760401dac401e970193ff0a
