### ISSUE TITLE
Export SNA: conserver l'extension PDF des délibérations

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-adresse-module#47]
Lors de la copie des fichiers de délibérations dans le fichier ZIP pour l'export SNA, l'extension PDF des documents est perdu.

Il faut récupérer l'extension de `$value->lien` pour le réutiliser dans `addFile` https://github.com/3liz/lizmap-adresse-module/blob/master/adresse/controllers/service.classic.php#L330

**Comment by drillinP** [comment]
Commit d0afe216cf79c1a48a070bcb9fdd2775be3a4884
