### ISSUE TITLE
Export BAL: des colonnes manquent pour correspondre à la BAL v1.2

### ISSUE THREAD

**Issue by rldhont** [3liz/lizmap-adresse-module#48]
La requête actuelle renvois : 
* cle_interop
* uid_adresse
* voie_nom
* numero
* suffixe
* commune_nom
* position
* x
* y
* long
* lat
* source
* date_der_maj

https://github.com/3liz/lizmap-adresse-module/blob/master/adresse/classes/search.class.php#L18

Il manque :
* commune_insee
* commune_deleguee_insee
* commune_deleguee_nom
* lieudit_complement_nom
* cad_parcelles

Il en est de même pour l'export CSV https://github.com/3liz/lizmap-adresse-module/blob/master/adresse/classes/exportDoc.class.php#L24

Il serait bien aussi de respecter l'ordre de la documentation https://aitf-sig-topo.github.io/voies-adresses/files/AITF_SIG_Topo_Format_Base_Adresse_Locale_v1.2.pdf
* uid_adresse
* cle_interop
* commune_insee
* commune_nom
* commune_deleguee_insee
* commune_deleguee_nom
* voie_nom
* lieudit_complement_nom
* numero
* suffixe
* position
* x
* y
* long
* lat
* cad_parcelles
* source
* date_der_maj

**Comment by drillinP** [comment]
@rldhont  dans le modèles actuels nous n'avons pas de champs `cad_parcelles` il faudrait le rajouter au modèle de données pour le calculer avec l'algo qui s'occupe des parcelles ou alors le calculer dans la requête mais il faut aller chercher des données dans `cadastre`. Je pense que le premier choix est plus adapter ?

**Comment by drillinP** [comment]
Commit 8f5da92a7ca850fc7f61b609fbcb82650afbbb3b
