### ISSUE TITLE
Rafraîchissement de l'adresse sur les points adresses après modification de la voie

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-adresse-module#5]
* Lorsqu'on modifie le nom d'une voie depuis le formulaire de Lizmap, un trigger met à jour le libellé de la voie dans la table `adresse.point_adresse`
* Si dans la symbologie de la couche des points d'adresse, une étiquette a été configurée, on ne voit pas la modification sur la carte, car la couche n'est pas rafraîchie suite à l'édition de la couche des voies

Pour tester:

* vérifier si se déplacer sur la carte rafraîchit bien les étiquettes pour les points d'adresses liés à cette voie
* si oui, ajouter dans le module adresse la détection de l'événement Lizmap `lizmapeditionfeaturemodified` de modification d'une voie, et lancer alors automatiquement le rafraîchissement de la couche des points d'adresses. Lancer la méthode `redraw` sur la couche OpenLayers correspondante

@rldhont

**Comment by drillinP** [comment]
Rafraîchissement ok
