### ISSUE TITLE
Proposition d'un numéro "bis" alors qu'il y a la place pour d'autres numéros

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-adresse-module#7]
Lorsqu'on crée un nouveau point d'adresse via le formulaire d'édition, 

* pour une voie avec numérotation classique (non métrique)
* entre 2 points existants qui sont séparés de plus que 2, par exemple 2 et 10

Le script proposait "2 bis", alors qu'il y a la place pour 4, 6, 8.

**Comment by drillinP** [comment]
Ok dans le dernier PR "fix bugs" du plugin
