### ISSUE TITLE
Clarifier la fonction d'inversion du sens d'une voie

### ISSUE THREAD

**Issue by mdouchin** [3liz/lizmap-adresse-module#8]
Lorsque la voie est métrique, les numéros pairs/impairs ne sont pas bien attribués en fonction du sens de la voie et de la propriété `sens`, selon qu'on les place à gauche ou à droite.

Contexte à valider par @rldhont:
* un champ `sens` permet de dire "inverser la numérotation" et peut être à `false` (default) ou `true` (c'est-à-dire qu'on ne numérote pas selon le sens de la géométrie, mais dans le sens inverse)
* le sens de la géométrie est celui pris en compte, sauf si `sens` est `true`

Le bouton `Inverser` dans la popup fait 2 choses : 
* il inverse la géométrie ET 
* il passe `sens` à son opposé.

L'utilité de cette action est de pouvoir changer le sens de la géométrie sans changer la manière de numéroter.

A faire

- [x] Renommer le champ sens et le commenter pour le rendre intelligible
- [x] Corriger le bug de proposition de numéro en fonction du sens de la géométrie et de ce champ

@drillinP @rldhont

**Comment by rldhont** [comment]
Lié à ma demande https://github.com/3liz/qgis-gestion_base_adresse-plugin/issues/25 et à mon commentaires https://github.com/3liz/qgis-gestion_base_adresse-plugin/pull/26#discussion_r409642413

J'avais compris le champs `sens` comme une simple description des numéros pairs à droites ou à gauche en conservant le sens de la géométrie pour définir l'ordre des numéros.

**Comment by rldhont** [comment]
@mdouchin @drillinP quel est le point de vue du CD14 sur ce champs ?

**Comment by drillinP** [comment]
Alors j'ai eu une réponse du CD14 le bouton doit se charger d'inverser à la foit le sens de numérotation et le sens de la géométrie, voici le contenue du mail exact: 
Bonjour,
Merci pour les correction des bugs.
L’inversion du sens de la voie dans la pop-up lizmap doit permettre l’inversion de la géométrie ainsi que du sens de numérotation. Cette option est nécessaire pour les utilisateurs qui auraient tracé leur voie en sens inverse (en partant de la fin). Après inversion, la numérotation doit alors se faire de façon croissante depuis le point final du tracé de la voie.

**Comment by drillinP** [comment]
C'est ce que fait actuellement le bouton, je vais le tester plus précisément

**Comment by rldhont** [comment]
Modification proposée dans le plugin https://github.com/3liz/qgis-gestion_base_adresse-plugin/pull/26

**Comment by drillinP** [comment]
commit f951bb1

**Comment by drillinP** [comment]
commit f951bb1
